// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restouran.Infrastructure;

#nullable disable

namespace Restouran.Infrastructure.Migrations
{
    [DbContext(typeof(RestouranContext))]
    partial class RestouranContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Restouran.Infrastructure.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("TotalSpent")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Restouran.Infrastructure.Models.MenuItem", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("IdItem");

                    b.HasIndex("OrderId");

                    b.ToTable("MenuItems", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Restouran.Infrastructure.Models.MenuItemTag", b =>
                {
                    b.Property<int>("MenuItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MenuItemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("MenuItemTags");
                });

            modelBuilder.Entity("Restouran.Infrastructure.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Restouran.Infrastructure.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Restouran.Infrastructure.Models.Dessert", b =>
                {
                    b.HasBaseType("Restouran.Infrastructure.Models.MenuItem");

                    b.Property<string>("TemperatureService")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeOfDessert")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Desserts", (string)null);
                });

            modelBuilder.Entity("Restouran.Infrastructure.Models.MainDish", b =>
                {
                    b.HasBaseType("Restouran.Infrastructure.Models.MenuItem");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSpicy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeOfDish")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("MainDishes", (string)null);
                });

            modelBuilder.Entity("Restouran.Infrastructure.Models.MenuItem", b =>
                {
                    b.HasOne("Restouran.Infrastructure.Models.Order", "order")
                        .WithMany("MenuItem")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");
                });

            modelBuilder.Entity("Restouran.Infrastructure.Models.MenuItemTag", b =>
                {
                    b.HasOne("Restouran.Infrastructure.Models.MenuItem", "MenuItem")
                        .WithMany("MenuItemTags")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restouran.Infrastructure.Models.Tag", "Tag")
                        .WithMany("MenuItemTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Restouran.Infrastructure.Models.Order", b =>
                {
                    b.HasOne("Restouran.Infrastructure.Models.Customer", "customer")
                        .WithOne("order")
                        .HasForeignKey("Restouran.Infrastructure.Models.Order", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");
                });

            modelBuilder.Entity("Restouran.Infrastructure.Models.Dessert", b =>
                {
                    b.HasOne("Restouran.Infrastructure.Models.MenuItem", null)
                        .WithOne()
                        .HasForeignKey("Restouran.Infrastructure.Models.Dessert", "IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restouran.Infrastructure.Models.MainDish", b =>
                {
                    b.HasOne("Restouran.Infrastructure.Models.MenuItem", null)
                        .WithOne()
                        .HasForeignKey("Restouran.Infrastructure.Models.MainDish", "IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restouran.Infrastructure.Models.Customer", b =>
                {
                    b.Navigation("order");
                });

            modelBuilder.Entity("Restouran.Infrastructure.Models.MenuItem", b =>
                {
                    b.Navigation("MenuItemTags");
                });

            modelBuilder.Entity("Restouran.Infrastructure.Models.Order", b =>
                {
                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("Restouran.Infrastructure.Models.Tag", b =>
                {
                    b.Navigation("MenuItemTags");
                });
#pragma warning restore 612, 618
        }
    }
}
